AotTest.sh
AotWin.sh
ClearWin.sh
CompileIfaceGenCli.sh
Compose.sh
CpAssets.sh
Doc/
ExternalRsrc/
GitSubMod.sh
Languages/
Ngaq-Debug.sqlite
Ngaq.Core/
Ngaq.Frontend/
Ngaq.Local/
Ngaq.Server/
Ngaq.Sqlite
Ngaq.Test/
Ngaq.dev.sqlite
Ngaq.sln
PublishWin.sh
README.md
README.typ
RemakeDb.sh
RunBrowser.sh
RunWin.sh
Spec.typ
Test.sh
Todo/
Tsinswreng.AvlnTools/
Tsinswreng.CsCfg/
Tsinswreng.CsCore/
Tsinswreng.CsDictMapper/
Tsinswreng.CsFactoryMkr/
Tsinswreng.CsIfaceGen/
Tsinswreng.CsIfaceGen.Cli.exe
Tsinswreng.CsPage/
Tsinswreng.CsSqlHelper/
Tsinswreng.CsSrcGenTools/
Tsinswreng.CsTools/
Tsinswreng.CsTypeAlias/
Tsinswreng.CsUlid/
Tsinswreng.JavaSqlHelper/
UpdSln.sh
WebSrv.sh
WordList.typ
_Note/
assets/
ls
proj/
