dotnet sln add Ngan.Dict/Ngan.Dict.Core/proj/**/*.csproj
dotnet sln add Ngan.Dict/Ngan.Dict.Backend/proj/**/*.csproj
dotnet sln add Ngan.Dict/Ngan.Dict.Doc/proj/**/*.csproj
dotnet sln add Ngan.Dict/Ngan.Dict.Test/proj/**/*.csproj
dotnet sln add Ngan.Dict/Ngan.Dict.Frontend/proj/**/*.csproj
dotnet sln add Ngan.Dict/Ngan.Dict.Server/proj/**/*.csproj
dotnet sln add Ngan.Dict/Ngan.Dict.Scripts/proj/**/*.csproj

dotnet sln add Ngan.Ime/Ngan.Ime.Core/proj/**/*.csproj
dotnet sln add Ngan.Ime/Ngan.Ime.Doc/proj/**/*.csproj
dotnet sln add Ngan.Ime/Ngan.Ime.Frontend/proj/**/*.csproj
dotnet sln add Ngan.Ime/Ngan.Ime.Rime/proj/**/*.csproj

dotnet sln add AvlnImeDemo/**/*.csproj
dotnet sln add CsRimeApi/proj/**/*.csproj
dotnet sln add CsRimeLua/proj/**/*.csproj
dotnet sln add CsRimeLua/proj/TestLuaLib/proj/**/*.csproj
dotnet sln add RimeTools/proj/**/*.csproj
dotnet sln add RimeTts/proj/**/*.csproj

dotnet sln add Tsinswreng.CsInterop/proj/**/*.csproj
dotnet sln add Tsinswreng.CsLua/proj/**/*.csproj
dotnet sln add Tsinswreng.CsRingBuffer/proj/**/*.csproj
dotnet sln add Tsinswreng.CsSqlHelper/proj/**/*.csproj
dotnet sln add Tsinswreng.CsUlid/proj/**/*.csproj

dotnet sln add Tsinswreng.CsCore/proj/**/*.csproj
dotnet sln add Tsinswreng.CsCtx/proj/**/*.csproj
dotnet sln add Tsinswreng.CsTools/proj/**/*.csproj
dotnet sln add Tsinswreng.CsU128Id/proj/**/*.csproj
dotnet sln add Tsinswreng.CsI18n/proj/**/*.csproj
dotnet sln add Tsinswreng.CsErr/proj/**/*.csproj
dotnet sln add Tsinswreng.CsJson/proj/**/*.csproj
dotnet sln add Tsinswreng.CsSrcGenTools/proj/**/*.csproj
dotnet sln add Tsinswreng.CsFactoryMkr/proj/**/*.csproj
dotnet sln add Tsinswreng.CsDictMapper/proj/**/*.csproj
dotnet sln add Tsinswreng.Srefl/proj/**/*.csproj
dotnet sln add Tsinswreng.CsIfaceGen/proj/**/*.csproj
dotnet sln add Tsinswreng.CsDecl/proj/**/*.csproj
dotnet sln add Tsinswreng.CsSql/proj/**/*.csproj
dotnet sln add Tsinswreng.CsPage/proj/**/*.csproj
dotnet sln add Tsinswreng.CsLog/proj/**/*.csproj
dotnet sln add Tsinswreng.CsCfg/proj/**/*.csproj
dotnet sln add Tsinswreng.CsTempus/proj/**/*.csproj
dotnet sln add Tsinswreng.AvlnTools/proj/**/*.csproj
dotnet sln add Tsinswreng.Avln.Dsl/proj/**/*.csproj
dotnet sln add Tsinswreng.Avln.Grid/proj/**/*.csproj
dotnet sln add Tsinswreng.Avln.Navi/proj/**/*.csproj
dotnet sln add Tsinswreng.CsYamlMd/proj/**/*.csproj
dotnet sln add Tsinswreng.CsTextWithBlob/proj/**/*.csproj
dotnet sln add Tsinswreng.CsTreeTest/proj/**/*.csproj
dotnet sln add Tsinswreng.CsTreeTest/proj/Samples/**/*.csproj
dotnet sln add Tsinswreng.Cssh/proj/**/*.csproj
#dotnet sln add Tsinswreng.AvlnTools/Example/proj/**/*.csproj
dotnet sln add Tsinswreng.Avln.StrokeText/proj/**/*.csproj
#dotnet sln add Tsinswreng.Avln.StrokeText/Samples/StrokeText.Sample/**/*.csproj
dotnet sln add Thesis/proj/**/*.csproj
dotnet sln add Tsinswreng.OpenXmlTools/proj/**/*.csproj
