this file is generated by
```bash
cwln . -i cs$ -e bin -e obj
```

```cs
File: MyProj1.Test/MyProj1TestMgr.cs
01: using MyProj1.Test.MyDomains.Calculator;
02: using Tsinswreng.CsTreeTest;
03: 
04: namespace MyProj1.Test;
05: 
06: 
07: // Each csproj of test project should have a Test Manager
08: // and register all tester below
09: public class MyProj1TestMgr : DiEtTestMgr {
10: 	public static MyProj1TestMgr Inst = new();
11: 	public override ITestNode RegisterTestsInto(ITestNode? Test) {
12: 		Test = this.TestNode;
13: 		// 注册各个领域的测试器
14: 		this.RegisterTester<TestCalculator>();
15: 		return Test;
16: 	}
17: }

File: MyProj1.Test/Program.cs
1: using MyProj1.Test;
2: using Tsinswreng.CsTreeTest;
3: 
4: var mgr = MyProj1TestMgr.Inst;
5: ITestExecutor executor = new TreeTestExecutor();
6: await executor.RunEtPrint(mgr.TestNode);

File: MyProj1.Test/MyDomains/AnotherService/_TestAnotherService.cs

File: MyProj1.Test/MyDomains/Calculator/Calculator.cs
01: namespace MyProj1.Test.MyDomains.Calculator;
02: /// example Testee class. this is a sample proj , we put it here for convenience
03: /// actually testee class are not in the same csproj as test code
04: public class Calculator {
05: 	public int Add(int a, int b) {
06: 		return a + b;
07: 	}
08: 	public bool TryIntDivide(int a, int b, out int R) {
09: 		if (b == 0) {
10: 			R = default;
11: 			return false;
12: 		}
13: 		R = a / b;
14: 		return true;
15: 	}
16: }

File: MyProj1.Test/MyDomains/Calculator/TestAdd.cs
01: using Tsinswreng.CsTreeTest;
02: 
03: namespace MyProj1.Test.MyDomains.Calculator;
04: // each part should only mainly test one function. in this part we test Add
05: public partial class TestCalculator {
06: 	public void RegisterAdd(ITestNode Node) {
07: 		var register = Node.MkTestFnRegister(
08: 			typeof(TestCalculator), // tester type
09: 			[typeof(Calculator)], // testee types
10: 			[nameof(MyDomains.Calculator.Calculator.Add)], // testee fn names, must use nameof()
11: 			"YourTestNamePrefix" // optional
12: 		);
13: 		var R = register.Register;
14: 		R("Add positive numbers", async (o) => {
15: 			var r = Calculator.Add(5, 3);
16: 			if (r != 8) {
17: 				throw new Exception($"Expected 8 but got {r}");
18: 			}
19: 			return null;
20: 		});
21: 		//you can change the props of `register` here and then you can still use `R` directly
22: 		//e.g. register.UniqNamePrefix = "NewPrefix";
23: 		R("Add positive and negative numbers", async (o) => {
24: 			var r = Calculator.Add(5, -3);
25: 			if (r != 2) {
26: 				throw new Exception($"Expected 2 but got {r}");
27: 			}
28: 			return null;
29: 		});
30: 	}
31: }

File: MyProj1.Test/MyDomains/Calculator/TestDivide.cs
01: using Tsinswreng.CsTreeTest;
02: 
03: namespace MyProj1.Test.MyDomains.Calculator;
04: 
05: public partial class TestCalculator {
06: 	public void RegisterTryIntDivide(ITestNode Node) {
07: 		var register = Node.MkTestFnRegister(
08: 			typeof(TestCalculator),
09: 			[typeof(Calculator)],
10: 			[nameof(MyDomains.Calculator.Calculator.TryIntDivide)],
11: 			"Divide"
12: 		);
13: 
14: 		var R = register.Register;
15: 
16: 		R("positive", async (o) => {
17: 			if(!Calculator.TryIntDivide(20, 4, out var R)){
18: 				throw new Exception("Expected true but got false");
19: 			}
20: 			if(R != 5){
21: 				throw new Exception($"Expected 5 but got {R}");
22: 			}
23: 			return null;
24: 		});
25: 		R("Divide by zero", async (o) => {
26: 			if(Calculator.TryIntDivide(20, 0, out var R)){
27: 				throw new Exception("Expected false but got true");
28: 			}
29: 			return null;
30: 		});
31: 	}
32: }

File: MyProj1.Test/MyDomains/Calculator/_TestCalculator.cs
01: //we suggest one tester class corresponds to one testee class.
02: // and put different tester classes in separates folders.
03: //now we are in Calculator/ , this is only for `TestCalculator`
04: using Tsinswreng.CsTreeTest;
05: 
06: namespace MyProj1.Test.MyDomains.Calculator;
07: 
08: //Use partial class. this is the main part. the file name of main part should start with _
09: // each part of the class should only test one method
10: // the main part should not do test but assemble the test cases in other parts.
11: public partial class TestCalculator : ITester {
12: 	Calculator Calculator;
13: 	public TestCalculator() {
14: 		//you can also use dependency injection
15: 		Calculator = new Calculator();
16: 	}
17: 	
18: 	public ITestNode RegisterTestsInto(ITestNode? Test) {
19: 		Test ??= new TestNode();
20: 		//default is false, if set to true, the tests in this node will run in order.
21: 		Test.Ordered = false;
22: 
23: 		RegisterAdd(Test);
24: 		RegisterTryIntDivide(Test);
25: 		return Test;
26: 	}
27: }


```
